version: "3.9"
services:
  db:
    build: 
      context: ./
      dockerfile: ./database.dockerfile
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - .:/domain
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ParkThis
